### ISSUE TITLE
Non rimuove le personalizzazioni

### ISSUE THREAD

**Issue by daimpa** [InforgeNet/XFItalianTranslation#22]
Non riesco a scaricare il language pack senza personalizzazioni. Cliccando su "Rimuovi personalizzazioni" affianco a "language-Italiano.xml" viene fuori "Some checks were not successful - 2 failing and 2 successful checks"

**Comment by murdercode** [comment]
L'XML dovrebbe essere già senza personalizzazioni (ultima commit), mi fai un esempio di dove le trovi?
Thanks,

**Comment by daimpa** [comment]
Nel Footer mi sono ritrovato quanto segue, inoltre mi sono ritrovato nel forum tutte le etichette che utilizzate su tomshw.

3LABS S.R.L. • Via Dante 16 - Milano (MI) 20121 CF/P.IVA: 04146420965 - REA: MI - 1729249 - Capitale Sociale: 10.000 euro

© 2024 3Labs Srl. Tutti i diritti riservati.

**Comment by murdercode** [comment]
Ho rimosso a mano tutte le custom, sembra ci fosse un bug sulla versione di XF che abbiamo usato per fare la traduzione
Ora dovrebbe essere ok: https://github.com/InforgeNet/XFItalianTranslation/releases/tag/v2.3.1

Fammi sapere ;)

**Comment by daimpa** [comment]
Grazie, in settimana provo! :)

**Comment by daimpa** [comment]
Confermo che mi sembra tutto risolto
