### ISSUE TITLE
La traduzione dovrebbe contenere solo XenForo

### ISSUE THREAD

**Issue by SpeedJack** [InforgeNet/XFItalianTranslation#9]
Il file language-italiano.xml in questo repository dovrebbe contenere solo frasi del core di XenForo, ossia con:
`addon_id="XF"`
Attualmente contiene anche frasi di vari addon, quali:
- XenForge/UsernameChange (addon di terze parti)
- XFRM (XenForo Resource Manager: anche se è di XenForo, è comunque meglio separarlo in quanto non tutte le board lo installano)
- Andy/WeeklyDigest (addon di terze parti)
- BR_SupportTicketSystem (addon per XenForo 1.x - queste non dovrebbero proprio starci)

Le traduzioni di questi addon dovrebbero stare in repository separati.

**Comment by AlessioDP** [comment]
Ho effettuato l'esportazione del solo file di lingua dell'addon XenForo (solo board), spuntando l'inserimento delle frasi non modificate quindi ancora in inglese.

Il cambiamento è nel nome del file che passa da `language-italiano.xml` a `language-italiano-XF.xml`.
